# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#repos:
#- repo: https://github.com/jumanjihouse/pre-commit-hooks
#  rev: 2.1.5
#  hooks:
#    - id: shellcheck
#      types: [executable, text]
#      args: [-i, SC2086]